# Generated by Django 5.2.2 on 2025-08-25 10:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board_messages', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.DeleteModel(
            name='MessageComment',
        ),
    ]
