# Generated by Django 5.2.11 on 2026-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_board_messages", "0004_alter_message_content_delete_messagecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="comments_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="likes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="views",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
