# Generated by Django 5.2.11 on 2026-02-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_board_messages", "0006_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
